[package]
name = "impulse_actuator"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { path = "../impulse_dependency_tokio", package = "impulse_dependency_tokio", features = [ "fs", "process" ] }

[dev-dependencies]
tokio = { path = "../impulse_dependency_tokio", package = "impulse_dependency_tokio", features = [ "macros", "rt-multi-thread" ] }
